services:
  kingshot-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kingshot-discord-bot-local
    container_name: kingshot-discord-bot
    volumes:
      - /opt/docker/kingshot/db/:/app/db
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=<your bot token here>
